---
title: "Resumen de Librería PURR"
author: "Christian Gabriel Bernedo"
date: "31/1/2022"
output: github_document
---
### La librería PURR podemos encontrarla en la colección tidyverse, este paquete es una herramienta que quisas no es tan conocida como otras de tidyverse como dplyr o ggplort2, pero esta tambien es muy importante como herramienta funcioanal de programación en R.

### Se dice que es una herramienta funcional en programación de R porque es sinteticamente estable, tambien se puede recordar sencillamente, a su vez simplifica diversos códigos de tidyverse, pero un punto negativo es que se ejecuta más lento que las funciones lapply.

### Esta librería trabaja con listas y en ella puede: filtrar, resumir, cambiar formas o unirlas, además de crear blucles for.

### Por ultimo su función estrella es "map", esta aplica una función determinada a cada elemento de una lista. De ella se derivan otras funciones como map2 o map.

## Ejemplo:
```{r}
library(tidyverse)
marcas=c("nissan","toyota","chebrolet")
años=c(1997,1965,2008)
pais=c("España", "Mexico", "Perú")
autos=list("marcas", "años","pais") 
# calcular el numero de elemento de cada sublista
map_int(autos, length)
```


